
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 3000
  selector:
    app: myapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 361509912577.dkr.ecr.eu-west-1.amazonaws.com/myapp:dummy
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 3000
      imagePullSecrets:
          - name: regcred